##To test your GitHub Action CI/CD is working use the below code

#main.yaml
name: Check Compute List

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_LOG: INFO
  project_id: $PROJECT_ID
  GCP_REGION: $GCP_REGION
  GCP_ZONE: $GCP_ZONE
  
jobs:
  gcloud-setup:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        # token_format: 'access_token'
        workload_identity_provider: ${{ secrets.POOL_URL }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}
        gcp_zone: ${{ env.GCP_REGION }}
        
    - name: 'List Compute Instances'
      run: |-
        gcloud compute instances list
